Repository jolicode/elastically, pull requests merged in 2020-10, with the labels that each got.

#40 Fix issue while dealing with prefixed Index.
  src/IndexBuilder.php
Labels: Hacktoberfest, good first issue

#44 Add CHANGELOG
  CHANGELOG.md
Labels: Hacktoberfest, hacktoberfest-accepted

#47 Code refactor.
  src/Indexer.php
Labels: hacktoberfest-accepted
